repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        files: classification_project
        args: ['--line-length=120', '--target-version=py310']
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      -   id: flake8
          files: classification_project
          args: [
              '--max-line-length=120',
              '--max-complexity=10',
              '--per-file-ignores=__init__.py:F401,main.py:C901',
              '--extend-ignore=E203',
              '--exclude=.git,__pycache__,_version.py',
          ]
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      -   id: isort
          files: classification_project
          args: ['--profile=black']