dataset:
  train_data_path: train_data
  val_data_path: val_data
  test_data_path: test_data
  train_sample: 1000
  batch_size: 256
  img_height: 96
  img_width: 96
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
model_training:
  n_epochs: 3
  learning_rate: 0.001
  device: cpu
  cpt_path: model_checkpoints/cat_dog_cls_resnet18_v1.cp
model_inference:
  pred_path: pred.csv
mlflow:
  address: 128.0.1.1:8080