name: pre-commit

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install poetry==1.6.1
          poetry config virtualenvs.create false \
          && poetry install --no-interaction --no-cache --no-root --without dev
      - name: Run pre-commit
        run: pre-commit run --all-files